// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCln4bKIGHMYjrmtqaO9ZlZwPZZRtCQ4ww',
    appId: '1:799353460729:web:5fd1c9e1e977dea5d88f28',
    messagingSenderId: '799353460729',
    projectId: 'atmostrack',
    authDomain: 'atmostrack.firebaseapp.com',
    storageBucket: 'atmostrack.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwl3lT4EMARAPtrGP-wXoFo_A6uHSoSYM',
    appId: '1:799353460729:android:47ce3326a8e519ddd88f28',
    messagingSenderId: '799353460729',
    projectId: 'atmostrack',
    storageBucket: 'atmostrack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxOhNJ973aUHbl3kP7y6vAaEIBH0wRh-E',
    appId: '1:799353460729:ios:12f7a67d6eaa5e5dd88f28',
    messagingSenderId: '799353460729',
    projectId: 'atmostrack',
    storageBucket: 'atmostrack.appspot.com',
    iosBundleId: 'com.example.atmostrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxOhNJ973aUHbl3kP7y6vAaEIBH0wRh-E',
    appId: '1:799353460729:ios:e3ee5896ca2e080ed88f28',
    messagingSenderId: '799353460729',
    projectId: 'atmostrack',
    storageBucket: 'atmostrack.appspot.com',
    iosBundleId: 'com.example.atmostrack.RunnerTests',
  );
}
